######################################################################
# Automatically generated by qmake (3.0) lun set 15 16:11:07 2014
######################################################################

QT += widgets gui webkitwidgets
TEMPLATE = app
TARGET = qtgeo
INCLUDEPATH += . include

# Input
HEADERS += interfaccia.h ui_interfaccia.h include/localizzazione.hpp
FORMS += interfaccia.ui
SOURCES += interfaccia.cpp main.cpp src/localizzazione.cpp
